# Generated by Django 5.2.11 on 2026-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField()),
                ('processing_status', models.CharField(default='received', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type'], name='payments_st_event_t_802e5e_idx'), models.Index(fields=['stripe_account_id'], name='payments_st_stripe__f77e0a_idx')],
            },
        ),
    ]
