# Generated by Django 5.2.11 on 2026-03-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('amount_cents', models.IntegerField()),
                ('stripe_status', models.CharField(db_index=True, default='created', max_length=50)),
                ('stripe_environment', models.CharField(db_index=True, default='test', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField()),
                ('processing_status', models.CharField(default='received', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type'], name='payments_st_event_t_802e5e_idx'), models.Index(fields=['stripe_account_id'], name='payments_st_stripe__f77e0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('stripe_refund_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_environment', models.CharField(db_index=True, default='test', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='clients.clientticket')),
                ('client_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='payments.clientpayment')),
            ],
            options={
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='payments_cl_ticket__e5a3cd_idx'), models.Index(fields=['stripe_environment'], name='payments_cl_stripe__0a8ff8_idx')],
            },
        ),
    ]
