# Generated by Django 5.2.11 on 2026-02-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_platformledgerentry_uniq_final_ledger_per_job'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount_cents', models.IntegerField()),
                ('stripe_status', models.CharField(db_index=True, default='created', max_length=50)),
                ('stripe_environment', models.CharField(db_index=True, default='test', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.job')),
            ],
        ),
    ]
