# Generated by Django 5.2.11 on 2026-02-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientticket_snapshot_hash'),
        ('payments', '0002_clientpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ClientCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, default='')),
                ('stripe_refund_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_environment', models.CharField(db_index=True, default='test', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='payments.clientpayment')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='clients.clientticket')),
            ],
            options={
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='payments_cl_ticket__e5a3cd_idx'), models.Index(fields=['stripe_environment'], name='payments_cl_stripe__0a8ff8_idx')],
            },
        ),
    ]
