# Generated by Django 5.2.11 on 2026-02-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_clientpayment_stripe_charge_id_clientcreditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcreditnote',
            name='currency',
            field=models.CharField(default='CAD', max_length=10),
        ),
    ]
