# Generated by Django 5.2.11 on 2026-03-10 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service_type", "0003_alter_requiredcertification_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("province_code", models.CharField(db_index=True, max_length=10)),
                ("certificate_name", models.CharField(blank=True, max_length=255)),
                ("insurance_required", models.BooleanField(default=False)),
                ("certificate_required", models.BooleanField(default=False)),
                ("is_mandatory", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_rules",
                        to="service_type.servicetype",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_rule",
                "ordering": ["province_code", "service_type_id", "certificate_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="compliancerule",
            constraint=models.UniqueConstraint(
                fields=("province_code", "service_type", "certificate_name"),
                name="uq_compliance_rule_scope_certificate",
            ),
        ),
    ]
