# Generated by Django 5.2.11 on 2026-02-10 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('service_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('country', models.CharField(default='Canada', max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('is_asap', models.BooleanField(default=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_start_time', models.TimeField(blank=True, null=True)),
                ('estimated_duration_min', models.PositiveIntegerField(default=60)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_jobs', to='providers.provider')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service_type.servicetype')),
            ],
        ),
    ]
