# Generated by Django 5.2.11 on 2026-03-04 17:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('response_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobBroadcastAttempt',
            fields=[
                ('attempt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=16)),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'jobs_job_broadcast_attempt',
            },
        ),
        migrations.CreateModel(
            name='JobDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(db_index=True)),
                ('provider_id', models.IntegerField(db_index=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('public_resolution_note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'job_dispute',
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('posted', 'posted'), ('search_started', 'search_started'), ('offer_made', 'offer_made'), ('provider_accepted', 'provider_accepted'), ('client_confirm_requested', 'client_confirm_requested'), ('client_confirmed', 'client_confirmed'), ('assigned', 'assigned'), ('timeout', 'timeout'), ('cancelled', 'cancelled')], db_index=True, max_length=40)),
                ('provider_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('assignment_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'job_event',
            },
        ),
        migrations.CreateModel(
            name='JobFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('adjustment_reason', models.CharField(blank=True, default='', max_length=255)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('authorization_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('captured_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('voided', 'Voided'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs_job_financial',
            },
        ),
        migrations.CreateModel(
            name='JobMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_by', models.CharField(choices=[('client', 'Client'), ('provider', 'Provider')], max_length=10)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('phase', models.CharField(choices=[('pre_service', 'Pre-service'), ('in_progress', 'In-progress'), ('post_service', 'Post-service'), ('dispute', 'Dispute')], default='pre_service', max_length=20)),
                ('file', models.FileField(upload_to='job_media/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jobs_job_media',
            },
        ),
        migrations.CreateModel(
            name='KpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('window_hours', models.IntegerField(db_index=True, default=168)),
                ('payload_json', models.TextField()),
            ],
            options={
                'db_table': 'kpi_snapshot',
            },
        ),
        migrations.CreateModel(
            name='PlatformLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('gross_cents', models.IntegerField(default=0)),
                ('tax_cents', models.IntegerField(default=0)),
                ('fee_cents', models.IntegerField(default=0)),
                ('net_provider_cents', models.IntegerField(default=0)),
                ('platform_revenue_cents', models.IntegerField(default=0)),
                ('fee_payer', models.CharField(choices=[('client', 'Client'), ('provider', 'Provider'), ('split', 'Split')], default='client', max_length=8)),
                ('tax_region_code', models.CharField(blank=True, max_length=8, null=True)),
                ('is_adjustment', models.BooleanField(db_index=True, default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_run_id', models.CharField(blank=True, max_length=64, null=True)),
                ('finalize_version', models.PositiveSmallIntegerField(default=1)),
                ('rebuild_count', models.PositiveIntegerField(default=0)),
                ('last_rebuild_at', models.DateTimeField(blank=True, null=True)),
                ('last_rebuild_run_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_rebuild_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('quoted_urgent_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quoted_urgent_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_mode', models.CharField(choices=[('on_demand', 'On demand'), ('scheduled', 'Scheduled')], db_index=True, default='scheduled', max_length=20)),
                ('job_status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('waiting_provider_response', 'Waiting Provider Response'), ('pending_client_decision', 'Pending Client Decision'), ('hold', 'Hold'), ('pending_provider_confirmation', 'Pending provider confirmation'), ('pending_client_confirmation', 'Pending client confirmation'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=40)),
                ('cancelled_by', models.CharField(blank=True, choices=[('client', 'Client'), ('provider', 'Provider'), ('system', 'System')], max_length=20, null=True)),
                ('cancel_reason', models.CharField(blank=True, choices=[('dispute_approved', 'Dispute approved'), ('provider_rejected', 'Provider rejected'), ('auto_timeout', 'Auto timeout'), ('system', 'System action')], max_length=40, null=True)),
                ('country', models.CharField(default='Canada', max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('is_asap', models.BooleanField(default=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_start_time', models.TimeField(blank=True, null=True)),
                ('estimated_duration_min', models.PositiveIntegerField(default=60)),
                ('quoted_service_skill_id', models.IntegerField(blank=True, null=True)),
                ('quoted_base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quoted_currency_code', models.CharField(default='CAD', max_length=3)),
                ('quoted_pricing_unit', models.CharField(default='fixed', max_length=20)),
                ('quoted_emergency_fee_type', models.CharField(default='none', max_length=10)),
                ('quoted_emergency_fee_value', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('quoted_base_price_cents', models.BigIntegerField(blank=True, null=True)),
                ('quoted_currency', models.CharField(blank=True, default='', max_length=3)),
                ('quoted_pricing_source', models.CharField(blank=True, default='', max_length=32)),
                ('quoted_provider_service_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('quoted_tax_rate_bps', models.PositiveIntegerField(blank=True, null=True)),
                ('quoted_total_price_cents', models.BigIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('next_alert_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('alert_attempts', models.IntegerField(default=0)),
                ('on_demand_tick_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('on_demand_tick_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('tick_attempts', models.PositiveIntegerField(default=0)),
                ('last_tick_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_tick_attempt_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('marketplace_attempts', models.IntegerField(default=0)),
                ('marketplace_search_started_at', models.DateTimeField(blank=True, null=True)),
                ('client_confirmation_started_at', models.DateTimeField(blank=True, null=True)),
                ('next_marketplace_alert_at', models.DateTimeField(blank=True, null=True)),
                ('marketplace_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='clients.client')),
            ],
            options={
                'db_table': 'jobs_job',
            },
        ),
    ]
