# Generated by Django 5.2.11 on 2026-03-04 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('providers', '0001_initial'),
        ('service_type', '0001_initial'),
        ('settlements', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hold_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_jobs', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='job',
            name='hold_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_jobs_as_worker', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='job',
            name='provider_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='providers.providerservice'),
        ),
        migrations.AddField(
            model_name='job',
            name='selected_provider',
            field=models.ForeignKey(blank=True, db_column='selected_provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_jobs', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='job',
            name='service_type',
            field=models.ForeignKey(db_column='service_type_id', on_delete=django.db.models.deletion.PROTECT, to='service_type.servicetype'),
        ),
        migrations.AddField(
            model_name='jobbroadcastattempt',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_attempts', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobbroadcastattempt',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_broadcast_attempts', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobevent',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobfinancial',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobmedia',
            name='job',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='kpisnapshot',
            index=models.Index(fields=['created_at', 'window_hours'], name='kpi_snapsho_created_2f6a0a_idx'),
        ),
        migrations.AddField(
            model_name='platformledgerentry',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='platformledgerentry',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='settlements.providersettlement'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('job_mode', 'scheduled'), _negated=True), ('scheduled_date__isnull', False), _connector='OR'), name='ck_job_scheduled_requires_date'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('job_mode', 'on_demand'), _negated=True), ('scheduled_date__isnull', True), _connector='OR'), name='ck_job_on_demand_requires_null_date'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancel_reason__isnull', False), ('job_status', 'cancelled')), models.Q(('job_status', 'cancelled'), _negated=True), _connector='OR'), name='cancel_reason_required_if_cancelled'),
        ),
        migrations.AddConstraint(
            model_name='jobbroadcastattempt',
            constraint=models.UniqueConstraint(fields=('job', 'provider'), name='uq_job_broadcast_attempt_one_per_provider_per_job'),
        ),
        migrations.AddIndex(
            model_name='jobevent',
            index=models.Index(fields=['job', 'event_type', 'created_at'], name='job_event_job_id_aad0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='platformledgerentry',
            index=models.Index(fields=['tax_region_code'], name='jobs_platfo_tax_reg_e8fec2_idx'),
        ),
        migrations.AddIndex(
            model_name='platformledgerentry',
            index=models.Index(fields=['fee_payer'], name='jobs_platfo_fee_pay_249a2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_adjustment', False)), fields=('job',), name='uniq_base_ledger_per_job'),
        ),
        migrations.AddConstraint(
            model_name='platformledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_adjustment', False), ('is_final', True)), fields=('job',), name='uniq_final_ledger_per_job'),
        ),
    ]
