# Generated by Django 5.2.11 on 2026-02-10 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('jobs', '0001_initial'),
        ('providers', '0001_initial'),
        ('service_type', '0002_alter_providerservicetype_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='job',
            name='selected_provider',
            field=models.ForeignKey(blank=True, db_column='selected_provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_jobs', to='providers.provider'),
        ),
        migrations.AlterField(
            model_name='job',
            name='service_type',
            field=models.ForeignKey(db_column='service_type_id', on_delete=django.db.models.deletion.PROTECT, to='service_type.servicetype'),
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs_job',
        ),
    ]
