# Generated by Django 5.2.11 on 2026-03-08 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('providers', '0005_providerserviceextra_providerservicesubservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requested_subservice_id_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requested_subservice_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('dispute_approved', 'Dispute approved'), ('provider_rejected', 'Provider rejected'), ('client_cancelled', 'Client cancelled'), ('auto_timeout', 'Auto timeout'), ('system', 'System action')], max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='JobRequestedExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name_snapshot', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_extras', to='jobs.job')),
                ('provider_service_extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_job_extras', to='providers.providerserviceextra')),
            ],
            options={
                'db_table': 'job_requested_extra',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
