# Generated by Django 5.2.11 on 2026-02-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_client_alter_job_selected_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_mode',
            field=models.CharField(choices=[('on_demand', 'On demand'), ('scheduled', 'Scheduled')], db_index=True, default='scheduled', max_length=20),
        ),
    ]
