# Generated by Django 5.2.11 on 2026-03-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_requested_subservice_id_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="access_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="job",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
