# Generated by Django 5.2.11 on 2026-02-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_job_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('confirmed', 'Confirmed')], default='draft', max_length=20),
        ),
    ]
