# Generated by Django 5.2.11 on 2026-02-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='next_alert_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
