# Generated by Django 5.2.11 on 2026-02-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_next_alert_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='alert_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
