# Generated by Django 5.2.11 on 2026-03-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_requested_base_line_total_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='provider_service_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
