# Generated by Django 5.2.11 on 2026-02-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_alert_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quoted_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='quoted_currency_code',
            field=models.CharField(default='CAD', max_length=3),
        ),
        migrations.AddField(
            model_name='job',
            name='quoted_emergency_fee_type',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='quoted_emergency_fee_value',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='quoted_pricing_unit',
            field=models.CharField(default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='quoted_service_skill_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
