# Generated by Django 5.2.11 on 2026-03-10 02:38

import math
from django.db import migrations, models


GRID_SIZE_DEGREES = 0.05


def backfill_job_location_grid(apps, schema_editor):
    JobLocation = apps.get_model("jobs", "JobLocation")

    for location in JobLocation.objects.all().only("pk", "latitude", "longitude"):
        if location.latitude is None or location.longitude is None:
            continue
        JobLocation.objects.filter(pk=location.pk).update(
            grid_lat=math.floor(float(location.latitude) / GRID_SIZE_DEGREES),
            grid_lng=math.floor(float(location.longitude) / GRID_SIZE_DEGREES),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_joblocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblocation',
            name='grid_lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblocation',
            name='grid_lng',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_job_location_grid, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='joblocation',
            index=models.Index(fields=['grid_lat', 'grid_lng'], name='ix_job_location_grid'),
        ),
    ]
