# Generated by Django 5.2.11 on 2026-02-13 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_job_status'),
        ('providers', '0010_providerskillprice_emergency_fee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hold_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_jobs', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='job',
            name='quoted_urgent_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='quoted_urgent_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
