# Generated by Django 5.2.11 on 2026-03-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_joblocation_grid_lat_joblocation_grid_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobbroadcastattempt',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=16),
        ),
    ]
