# Generated by Django 5.2.11 on 2026-02-21 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_hold_expires_at_job_hold_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_by', models.CharField(choices=[('client', 'Client'), ('provider', 'Provider')], max_length=10)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('phase', models.CharField(choices=[('pre_service', 'Pre-service'), ('in_progress', 'In-progress'), ('post_service', 'Post-service'), ('dispute', 'Dispute')], default='pre_service', max_length=20)),
                ('file', models.FileField(upload_to='job_media/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='jobs.job')),
            ],
            options={
                'db_table': 'jobs_job_media',
            },
        ),
    ]
