# Generated by Django 5.2.11 on 2026-03-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_jobbroadcastattempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requested_tax_rate_bps_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requested_tax_region_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='requested_tax_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
