# Generated by Django 5.2.11 on 2026-02-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('jobs', '0011_alter_job_job_status'),
        ('providers', '0010_providerskillprice_emergency_fee_type_and_more'),
        ('workers', '0003_alter_worker_city_alter_worker_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hold_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_jobs_as_worker', to='workers.worker'),
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('staff_accepted', 'Staff accepted'), ('client_confirmed', 'Client confirmed'), ('staff_cancelled', 'Staff cancelled'), ('client_cancelled', 'Client cancelled'), ('service_started', 'Service started'), ('service_completed', 'Service completed'), ('hold_expired', 'Hold expired')], max_length=30)),
                ('actor_type', models.CharField(choices=[('staff', 'Staff'), ('client', 'Client'), ('system', 'System'), ('provider_admin', 'Provider admin')], max_length=20)),
                ('job_status_snapshot', models.CharField(blank=True, default='', max_length=40)),
                ('eta_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_events', to='clients.client')),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.job')),
                ('provider', models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_events', to='providers.provider')),
                ('worker', models.ForeignKey(blank=True, db_column='worker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_events', to='workers.worker')),
            ],
            options={
                'db_table': 'jobs_job_event',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='jobs_job_ev_job_id_14f6dc_idx'), models.Index(fields=['event_type', 'created_at'], name='jobs_job_ev_event_t_72d42f_idx')],
            },
        ),
    ]
