# Generated by Django 5.2.11 on 2026-03-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_job_requested_tax_rate_bps_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobevent",
            name="actor_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("system", "System"),
                    ("client", "Client"),
                    ("provider", "Provider"),
                    ("worker", "Worker"),
                    ("admin", "Admin"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobevent",
            name="payload_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobevent",
            name="visible_status",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="jobevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("posted", "posted"),
                    ("search_started", "search_started"),
                    ("offer_made", "offer_made"),
                    ("provider_accepted", "provider_accepted"),
                    ("client_confirm_requested", "client_confirm_requested"),
                    ("client_confirmed", "client_confirmed"),
                    ("assigned", "assigned"),
                    ("timeout", "timeout"),
                    ("cancelled", "cancelled"),
                    ("job_created", "job_created"),
                    ("waiting_provider_response", "waiting_provider_response"),
                    ("job_accepted", "job_accepted"),
                    ("job_in_progress", "job_in_progress"),
                    ("job_completed", "job_completed"),
                    ("job_cancelled", "job_cancelled"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
