# Generated by Django 5.2.11 on 2026-02-21 17:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_hold_worker_jobevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('adjustment_reason', models.CharField(blank=True, default='', max_length=255)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('authorization_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('captured_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('voided', 'Voided'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='jobs.job')),
            ],
            options={
                'db_table': 'jobs_job_financial',
            },
        ),
    ]
