# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_jobfinancial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(job_mode="scheduled")
                    | models.Q(scheduled_date__isnull=False)
                ),
                name="ck_job_scheduled_requires_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(job_mode="on_demand")
                    | models.Q(scheduled_date__isnull=True)
                ),
                name="ck_job_on_demand_requires_null_date",
            ),
        ),
    ]
