# Generated by Django 5.2.11 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_alter_jobevent_event_type_add_job_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("posted", "posted"),
                    ("search_started", "search_started"),
                    ("offer_made", "offer_made"),
                    ("provider_accepted", "provider_accepted"),
                    ("client_confirm_requested", "client_confirm_requested"),
                    ("client_confirmed", "client_confirmed"),
                    ("assigned", "assigned"),
                    ("timeout", "timeout"),
                    ("cancelled", "cancelled"),
                    ("job_created", "job_created"),
                    ("waiting_provider_response", "waiting_provider_response"),
                    ("job_accepted", "job_accepted"),
                    ("provider_declined", "provider_declined"),
                    ("job_in_progress", "job_in_progress"),
                    ("job_completed", "job_completed"),
                    ("job_expired", "job_expired"),
                    ("job_cancelled", "job_cancelled"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
