# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_job_mode_schedule_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="on_demand_tick_scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
