# Generated by Django 5.2.11 on 2026-03-14 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_alter_jobevent_event_type_add_provider_declined"),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobProviderExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[("declined", "Declined")],
                        default="declined",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_exclusions",
                        to="jobs.job",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_exclusions",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "db_table": "jobs_job_provider_exclusion",
            },
        ),
        migrations.AddConstraint(
            model_name="jobproviderexclusion",
            constraint=models.UniqueConstraint(
                fields=("job", "provider"),
                name="uq_job_provider_exclusion_one_per_provider_per_job",
            ),
        ),
    ]
