# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0015_job_on_demand_tick_scheduled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="on_demand_tick_dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
