# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0016_job_on_demand_tick_dispatched_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="tick_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="last_tick_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="last_tick_attempt_reason",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
