# Generated by Django 6.0.2 on 2026-02-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0017_job_tick_audit_fields"),
        ("providers", "0010_providerskillprice_emergency_fee_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobBroadcastAttempt",
            fields=[
                ("attempt_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_attempts",
                        to="jobs.job",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_broadcast_attempts",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "db_table": "jobs_job_broadcast_attempt",
            },
        ),
        migrations.AddConstraint(
            model_name="jobbroadcastattempt",
            constraint=models.UniqueConstraint(
                fields=("job", "provider"),
                name="uq_job_broadcast_attempt_one_per_provider_per_job",
            ),
        ),
    ]
