# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0018_job_broadcast_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="marketplace_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="next_marketplace_alert_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="marketplace_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
