# Generated by Django 5.2.11 on 2026-02-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_job_marketplace_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('waiting_provider_response', 'Waiting Provider Response'), ('hold', 'Hold'), ('pending_provider_confirmation', 'Pending provider confirmation'), ('pending_client_confirmation', 'Pending client confirmation'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=40),
        ),
    ]
