# Generated by Django 5.2.11 on 2026-02-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_job_marketplace_search_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client_confirmation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
