# Generated by Django 5.2.11 on 2026-02-22 14:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_job_client_confirmation_started_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobevent',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='jobevent',
            name='jobs_job_ev_job_id_14f6dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobevent',
            name='jobs_job_ev_event_t_72d42f_idx',
        ),
        migrations.RemoveField(
            model_name='jobevent',
            name='actor_type',
        ),
        migrations.RemoveField(
            model_name='jobevent',
            name='client',
        ),
        migrations.RemoveField(
            model_name='jobevent',
            name='eta_minutes',
        ),
        migrations.RemoveField(
            model_name='jobevent',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='jobevent',
            name='job_status_snapshot',
        ),
        migrations.RemoveField(
            model_name='jobevent',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='jobevent',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='jobevent',
            name='worker',
        ),
        migrations.AddField(
            model_name='jobevent',
            name='assignment_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='jobevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='jobevent',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobevent',
            name='provider_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='event_type',
            field=models.CharField(choices=[('posted', 'posted'), ('search_started', 'search_started'), ('offer_made', 'offer_made'), ('provider_accepted', 'provider_accepted'), ('client_confirm_requested', 'client_confirm_requested'), ('client_confirmed', 'client_confirmed'), ('assigned', 'assigned'), ('timeout', 'timeout'), ('cancelled', 'cancelled')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='jobevent',
            index=models.Index(fields=['job', 'event_type', 'created_at'], name='job_event_job_id_aad0ff_idx'),
        ),
        migrations.AlterModelTable(
            name='jobevent',
            table='job_event',
        ),
    ]
