# Generated by Django 5.2.11 on 2026-02-22 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_alter_jobevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('window_hours', models.IntegerField(db_index=True, default=168)),
                ('payload_json', models.TextField()),
            ],
            options={
                'db_table': 'kpi_snapshot',
                'indexes': [models.Index(fields=['created_at', 'window_hours'], name='kpi_snapsho_created_2f6a0a_idx')],
            },
        ),
    ]
