# Generated by Django 5.2.11 on 2026-02-23 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientticketline_tax_rate_bps_and_more'),
        ('jobs', '0025_apiidempotencykey'),
        ('providers', '0017_providerticketline_tax_rate_bps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('gross_cents', models.BigIntegerField(default=0)),
                ('tax_cents', models.BigIntegerField(default=0)),
                ('fee_cents', models.BigIntegerField(default=0)),
                ('net_provider_cents', models.BigIntegerField(default=0)),
                ('platform_revenue_cents', models.BigIntegerField(default=0)),
                ('fee_payer', models.CharField(choices=[('client', 'Client'), ('provider', 'Provider'), ('split', 'Split')], default='client', max_length=10)),
                ('tax_region_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='clients.client')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='jobs.job')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='providers.provider')),
            ],
        ),
    ]
