# Generated by Django 5.2.11 on 2026-02-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_platformledgerentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformledgerentry',
            name='client',
        ),
        migrations.RemoveField(
            model_name='platformledgerentry',
            name='provider',
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='fee_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='fee_payer',
            field=models.CharField(choices=[('client', 'Client'), ('provider', 'Provider'), ('split', 'Split')], default='client', max_length=8),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='gross_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='net_provider_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='platform_revenue_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='tax_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='tax_region_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddIndex(
            model_name='platformledgerentry',
            index=models.Index(fields=['tax_region_code'], name='jobs_platfo_tax_reg_e8fec2_idx'),
        ),
        migrations.AddIndex(
            model_name='platformledgerentry',
            index=models.Index(fields=['fee_payer'], name='jobs_platfo_fee_pay_249a2b_idx'),
        ),
    ]
