# Generated by Django 5.2.11 on 2026-02-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_remove_platformledgerentry_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformledgerentry',
            name='finalize_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='platformledgerentry',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformledgerentry',
            name='finalized_run_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='platformledgerentry',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
