# Generated by Django 5.2.11 on 2026-02-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_platformledgerentry_finalize_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformledgerentry',
            name='last_rebuild_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformledgerentry',
            name='last_rebuild_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformledgerentry',
            name='last_rebuild_run_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='platformledgerentry',
            name='rebuild_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
