# Generated by Django 5.2.11 on 2026-02-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_platformledgerentry_last_rebuild_at_and_more'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformledgerentry',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='settlements.providersettlement'),
        ),
    ]
