# Generated by Django 5.2.11 on 2026-02-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_platformledgerentry_settlement'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformledgerentry',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='settlements.providersettlement'),
        ),
    ]
