# Generated by Django 5.2.11 on 2026-02-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_alter_platformledgerentry_settlement'),
        ('settlements', '0003_monthlysettlementclose'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='platformledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_final', True)), fields=('job',), name='uniq_final_ledger_per_job'),
        ),
    ]
