# Generated by Django 5.2.11 on 2026-02-26 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_platformledgerentry_uniq_final_ledger_per_job'),
        ('settlements', '0011_settlementpayment_stripe_environment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='platformledgerentry',
            name='uniq_final_ledger_per_job',
        ),
        migrations.AddField(
            model_name='platformledgerentry',
            name='is_adjustment',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='fee_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='gross_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='tax_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='platformledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_adjustment', False)), fields=('job',), name='uniq_base_ledger_per_job'),
        ),
        migrations.AddConstraint(
            model_name='platformledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_adjustment', False), ('is_final', True)), fields=('job',), name='uniq_final_ledger_per_job'),
        ),
    ]
