# Generated by Django 5.2.11 on 2026-02-27 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_remove_platformledgerentry_uniq_final_ledger_per_job_and_more'),
        ('providers', '0020_servicecategory_providerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='provider_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='providers.providerservice'),
        ),
    ]
