# Generated by Django 5.2.11 on 2026-02-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_job_provider_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('provider', 'Provider'), ('system', 'System')], max_length=20, null=True),
        ),
    ]
