# Generated by Django 5.2.11 on 2026-03-01 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_job_cancelled_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(db_index=True)),
                ('provider_id', models.IntegerField(db_index=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='jobs.job')),
            ],
            options={
                'db_table': 'job_dispute',
            },
        ),
    ]
