# Generated by Django 5.2.11 on 2026-03-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_jobdispute_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdispute',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
