# Generated by Django 5.2.11 on 2026-03-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_jobdispute_resolution_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdispute',
            name='public_resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
