# Generated by Django 5.2.11 on 2026-03-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_jobdispute_public_resolution_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('dispute_approved', 'Dispute approved'), ('provider_rejected', 'Provider rejected'), ('auto_timeout', 'Auto timeout'), ('system', 'System action')], max_length=40, null=True),
        ),
    ]
