# Generated by Django 5.2.11 on 2026-03-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientticket_snapshot_hash'),
        ('jobs', '0040_job_cancel_reason'),
        ('providers', '0026_marketplaceanalyticssnapshot_snapshot_version'),
        ('service_type', '0003_delete_providerservicetype'),
        ('workers', '0003_alter_worker_city_alter_worker_province_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancel_reason__isnull', False), ('job_status', 'cancelled')), models.Q(('job_status', 'cancelled'), _negated=True), _connector='OR'), name='cancel_reason_required_if_cancelled'),
        ),
    ]
