# Generated by Django 5.2.11 on 2026-03-04 17:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('jobs', '0001_initial'),
        ('service_type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceAnalyticsSnapshot',
            fields=[
                ('marketplace_analytics_snapshot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('snapshot_version', models.CharField(default='ANALYTICS_V1', max_length=50)),
                ('snapshot', models.TextField()),
            ],
            options={
                'db_table': 'marketplace_analytics_snapshot',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('self_employed', 'Self-employed'), ('company', 'Company')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('business_registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('contact_first_name', models.CharField(max_length=100)),
                ('contact_last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verification_attempts', models.IntegerField(default=0)),
                ('profile_completed', models.BooleanField(default=False)),
                ('service_area', models.CharField(blank=True, default='', max_length=255)),
                ('accepts_terms', models.BooleanField(default=True)),
                ('billing_profile_completed', models.BooleanField(default=True)),
                ('stripe_account_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_onboarding_completed', models.BooleanField(default=False)),
                ('stripe_account_status', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_details_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_charges_enabled', models.BooleanField(default=False)),
                ('stripe_payouts_enabled', models.BooleanField(default=False)),
                ('country', models.CharField(default='Canada', max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('service_radius_km', models.PositiveIntegerField(default=10)),
                ('availability_mode', models.CharField(default='manual', max_length=20)),
                ('is_available_now', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_jobs_count', models.PositiveIntegerField(default=0)),
                ('cancelled_jobs_count', models.PositiveIntegerField(default=0)),
                ('disputes_lost_count', models.PositiveIntegerField(default=0)),
                ('quality_warning_active', models.BooleanField(default=False)),
                ('restricted_until', models.DateTimeField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='ProviderBillingProfile',
            fields=[
                ('provider_billing_profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('self_employed', 'Self-employed'), ('company', 'Company')], max_length=20)),
                ('legal_name', models.CharField(blank=True, default='', max_length=200)),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('gst_hst_number', models.CharField(blank=True, default='', max_length=40)),
                ('qst_tvq_number', models.CharField(blank=True, default='', max_length=40)),
                ('neq_number', models.CharField(blank=True, default='', max_length=40)),
                ('bn_number', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.OneToOneField(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_billing_profile',
            },
        ),
        migrations.CreateModel(
            name='ProviderInvoiceSequence',
            fields=[
                ('provider_invoice_sequence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(blank=True, default='', max_length=30)),
                ('next_number', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.OneToOneField(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_seq', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_invoice_sequence',
            },
        ),
        migrations.CreateModel(
            name='ProviderReview',
            fields=[
                ('provider_review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_review', to='jobs.job')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderServiceArea',
            fields=[
                ('provider_service_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
            options={
                'db_table': 'provider_service_area',
            },
        ),
        migrations.CreateModel(
            name='ProviderTicket',
            fields=[
                ('provider_ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ref_type', models.CharField(max_length=30)),
                ('ref_id', models.BigIntegerField(db_index=True)),
                ('ticket_no', models.CharField(max_length=60)),
                ('stage', models.CharField(choices=[('estimate', 'Estimate'), ('final', 'Final')], default='estimate', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('finalized', 'Finalized'), ('void', 'Void')], default='open', max_length=20)),
                ('subtotal_cents', models.BigIntegerField(default=0)),
                ('tax_cents', models.BigIntegerField(default=0)),
                ('total_cents', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('tax_region_code', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_ticket',
            },
        ),
        migrations.CreateModel(
            name='ProviderTicketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('line_type', models.CharField(choices=[('base', 'Base service'), ('extra', 'Extra'), ('fee', 'Fee'), ('adjust', 'Adjustment')], max_length=16)),
                ('description', models.CharField(max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price_cents', models.IntegerField(default=0)),
                ('line_subtotal_cents', models.IntegerField(default=0)),
                ('tax_rate_bps', models.IntegerField(default=0)),
                ('tax_cents', models.IntegerField(default=0)),
                ('line_total_cents', models.IntegerField(default=0)),
                ('tax_region_code', models.CharField(blank=True, max_length=10, null=True)),
                ('tax_code', models.CharField(blank=True, default='', max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='providers.providerticket')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('finance', 'Finance'), ('worker', 'Worker')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_users', to='providers.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['province', 'city', 'name'],
                'indexes': [models.Index(fields=['province', 'city'], name='ix_servicezone_prov_city')],
                'constraints': [models.UniqueConstraint(fields=('province', 'city', 'name'), name='uq_servicezone_province_city_name')],
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='providers.servicezone'),
        ),
        migrations.CreateModel(
            name='ProviderCertificate',
            fields=[
                ('provider_certificate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cert_type', models.CharField(max_length=80)),
                ('cert_name', models.CharField(blank=True, default='', max_length=150)),
                ('taken_at', models.CharField(blank=True, default='', max_length=150)),
                ('issued_by', models.CharField(blank=True, default='', max_length=150)),
                ('issued_country', models.CharField(blank=True, default='', max_length=80)),
                ('issued_city', models.CharField(blank=True, default='', max_length=80)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expires_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('declared', 'Declared'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='declared', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_certificate',
                'indexes': [models.Index(fields=['provider', 'status'], name='ix_prov_cert_status'), models.Index(fields=['cert_type'], name='ix_prov_cert_type')],
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('billing_unit', models.CharField(choices=[('hour', 'Per Hour'), ('fixed', 'Fixed Price'), ('sqm', 'Per Square Meter'), ('km', 'Per Kilometer'), ('day', 'Per Day')], max_length=20)),
                ('price_cents', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.provider')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_services', to='service_type.servicetype')),
            ],
            options={
                'indexes': [models.Index(fields=['service_type', 'is_active'], name='ix_psvc_type_active'), models.Index(fields=['price_cents'], name='ix_psvc_price')],
            },
        ),
        migrations.CreateModel(
            name='ProviderSkillPrice',
            fields=[
                ('emergency_fee_type', models.CharField(default='none', max_length=10)),
                ('emergency_fee_value', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('provider_skill_price_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(default='CAD', max_length=3)),
                ('pricing_unit', models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly'), ('sqm', 'Per m²'), ('linear_ft', 'Per linear ft'), ('item', 'Per item')], default='fixed', max_length=20)),
                ('min_qty', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_prices', to='providers.provider')),
                ('service_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_prices', to='service_type.serviceskill')),
            ],
            options={
                'db_table': 'provider_skill_price',
                'indexes': [models.Index(fields=['provider', 'is_active'], name='ix_psp_provider_active'), models.Index(fields=['service_skill', 'is_active'], name='ix_psp_skill_active')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'service_skill'), name='uq_provider_skill_price_provider_skill')],
            },
        ),
        migrations.AddIndex(
            model_name='providerticket',
            index=models.Index(fields=['provider', 'created_at'], name='ix_provider_ticket_created'),
        ),
        migrations.AddConstraint(
            model_name='providerticket',
            constraint=models.UniqueConstraint(fields=('provider', 'ticket_no'), name='uq_provider_ticket_no'),
        ),
        migrations.AddConstraint(
            model_name='providerticket',
            constraint=models.UniqueConstraint(fields=('provider', 'ref_type', 'ref_id'), name='uq_provider_ticket_ref'),
        ),
        migrations.AddIndex(
            model_name='providerticketline',
            index=models.Index(fields=['ticket', 'line_type'], name='ix_provider_line_ticket_type'),
        ),
        migrations.AddConstraint(
            model_name='providerticketline',
            constraint=models.UniqueConstraint(fields=('ticket', 'line_no'), name='uq_provider_ticket_line_no_per_ticket'),
        ),
        migrations.AddConstraint(
            model_name='provideruser',
            constraint=models.UniqueConstraint(fields=('provider', 'user'), name='uq_provider_user_unique'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['province', 'city', 'is_active'], name='ix_provider_geo_active'),
        ),
    ]
