# Generated by Django 5.2.11 on 2026-02-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('self_employed', 'Self-employed'), ('company', 'Company')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_first_name', models.CharField(max_length=100)),
                ('contact_last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(default='Canada', max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('service_radius_km', models.PositiveIntegerField(default=10)),
                ('availability_mode', models.CharField(default='manual', max_length=20)),
                ('is_available_now', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
    ]
