# Generated by Django 5.2.11 on 2026-03-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservice',
            name='compliance_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProviderInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_insurance', models.BooleanField(default=False)),
                ('insurance_company', models.CharField(blank=True, max_length=150)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='providers.provider')),
            ],
        ),
    ]
