# Generated by Django 5.2.11 on 2026-03-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providerservice_compliance_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='languages_spoken',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
