# Generated by Django 5.2.11 on 2026-02-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providerservicearea'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='providerservicearea',
            table='provider_service_area',
        ),
    ]
