# Generated by Django 5.2.11 on 2026-03-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_provider_languages_spoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='employee_count',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2_5', '2-5'), ('6_10', '6-10'), ('11_20', '11-20'), ('20_plus', '20+')], default='', max_length=10),
        ),
    ]
