# Generated by Django 5.2.11 on 2026-03-08 19:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_provider_employee_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderServiceExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('allows_quantity', models.BooleanField(default=True)),
                ('min_qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_qty', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('provider_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='providers.providerservice')),
            ],
            options={
                'db_table': 'provider_service_extra',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProviderServiceSubservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('provider_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='providers.providerservice')),
            ],
            options={
                'db_table': 'provider_service_subservice',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
