# Generated by Django 5.2.11 on 2026-02-12 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_providerservicearea_table_providerservicetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerservicearea',
            name='id',
        ),
        migrations.AddField(
            model_name='providerservicearea',
            name='provider_service_area_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='providerservicearea',
            name='provider',
            field=models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
        ),
        migrations.AlterModelTable(
            name='providerservicearea',
            table='provider_service_area',
        ),
        migrations.AlterModelTable(
            name='providerservicetype',
            table='provider_service_type',
        ),
    ]
