# Generated by Django 5.2.11 on 2026-03-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_providerserviceextra_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservicearea',
            name='postal_prefix',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
