# Generated by Codex on 2026-03-09

from math import log10

from django.db import migrations, models
from django.utils import timezone


def _clamp_score(value):
    return max(0.0, min(float(value or 0.0), 1.0))


def _operational_score(provider):
    completed = float(provider.completed_jobs_count or 0)
    cancelled = float(provider.cancelled_jobs_count or 0)
    total = completed + cancelled

    base_score = (completed / total) if total else 0.0
    if provider.quality_warning_active:
        base_score -= 0.15
    if provider.restricted_until and provider.restricted_until > timezone.now():
        base_score -= 0.50
    return round(_clamp_score(base_score), 4)


def _experience_score(provider):
    completed = float(provider.completed_jobs_count or 0)
    if completed <= 0:
        return 0.0
    return round(_clamp_score(log10(completed + 1.0) / 2.0), 4)


def _hybrid_score(provider, *, operational_score, experience_score):
    rating_score = _clamp_score((provider.avg_rating or 0) / 5)
    response_score = _clamp_score(provider.response_score)
    distance_score = _clamp_score(provider.distance_score)

    score = (
        (operational_score * 0.35)
        + (distance_score * 0.20)
        + (rating_score * 0.20)
        + (response_score * 0.15)
        + (experience_score * 0.10)
    )
    return round(_clamp_score(score), 4)


def backfill_provider_ranking_fields(apps, schema_editor):
    Provider = apps.get_model("providers", "Provider")

    for provider in Provider.objects.all().iterator():
        operational_score = _operational_score(provider)
        experience_score = _experience_score(provider)
        hybrid_score = _hybrid_score(
            provider,
            operational_score=operational_score,
            experience_score=experience_score,
        )
        Provider.objects.filter(pk=provider.pk).update(
            operational_score=operational_score,
            experience_score=experience_score,
            hybrid_score=hybrid_score,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0008_providerservicearea_postal_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="distance_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="provider",
            name="experience_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="provider",
            name="hybrid_score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name="provider",
            name="operational_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="provider",
            name="response_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.RunPython(backfill_provider_ranking_fields, migrations.RunPython.noop),
    ]
