# Generated by Django 5.2.11 on 2026-02-12 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_providerservicetype'),
        ('service_type', '0003_delete_providerservicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSkillPrice',
            fields=[
                ('provider_skill_price_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(default='CAD', max_length=3)),
                ('pricing_unit', models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly'), ('sqm', 'Per m²'), ('linear_ft', 'Per linear ft'), ('item', 'Per item')], default='fixed', max_length=20)),
                ('min_qty', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_prices', to='providers.provider')),
                ('service_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_prices', to='service_type.serviceskill')),
            ],
            options={
                'db_table': 'provider_skill_price',
                'indexes': [models.Index(fields=['provider', 'is_active'], name='ix_psp_provider_active'), models.Index(fields=['service_skill', 'is_active'], name='ix_psp_skill_active')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'service_skill'), name='uq_provider_skill_price_provider_skill')],
            },
        ),
    ]
