# Generated by Django 5.2.11 on 2026-02-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_providerskillprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerskillprice',
            name='emergency_fee_type',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='providerskillprice',
            name='emergency_fee_value',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
