# Generated by Codex on 2026-03-09

from django.db import migrations, models


def backfill_provider_metrics(apps, schema_editor):
    Provider = apps.get_model("providers", "Provider")
    ProviderMetrics = apps.get_model("providers", "ProviderMetrics")

    for provider in Provider.objects.all().iterator():
        jobs_completed = int(provider.completed_jobs_count or 0)
        jobs_cancelled = int(provider.cancelled_jobs_count or 0)
        jobs_accepted = max(jobs_completed + jobs_cancelled, 0)
        completion_rate = (jobs_completed / jobs_accepted) if jobs_accepted else 0.0
        acceptance_rate = float(provider.acceptance_rate or 0.0) / 100.0

        ProviderMetrics.objects.update_or_create(
            provider_id=provider.pk,
            defaults={
                "jobs_completed": jobs_completed,
                "jobs_accepted": jobs_accepted,
                "jobs_cancelled": jobs_cancelled,
                "avg_response_time": 0.0,
                "acceptance_rate": acceptance_rate,
                "completion_rate": completion_rate,
                "experience_score": float(provider.experience_score or 0.0),
                "operational_score": float(provider.operational_score or 0.0),
                "response_score": float(provider.response_score or 0.0),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0009_provider_ranking_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobs_completed", models.IntegerField(default=0)),
                ("jobs_accepted", models.IntegerField(default=0)),
                ("jobs_cancelled", models.IntegerField(default=0)),
                ("avg_response_time", models.FloatField(default=0.0)),
                ("acceptance_rate", models.FloatField(default=0.0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("experience_score", models.FloatField(default=0.0)),
                ("operational_score", models.FloatField(default=0.0)),
                ("response_score", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name="metrics",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "db_table": "provider_metrics",
            },
        ),
        migrations.RunPython(backfill_provider_metrics, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="provider",
            name="experience_score",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="operational_score",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="response_score",
        ),
    ]
