# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0010_providerskillprice_emergency_fee_type_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="providerservicetype",
            index=models.Index(
                fields=["provider", "service_type"],
                name="idx_pst_prov_st",
            ),
        ),
        migrations.AddIndex(
            model_name="providerservicetype",
            index=models.Index(
                fields=["service_type", "provider"],
                name="idx_pst_st_prov",
            ),
        ),
        migrations.AddIndex(
            model_name="providerservicetype",
            index=models.Index(
                fields=["service_type", "is_active", "provider"],
                name="idx_pst_st_act_prov",
            ),
        ),
        migrations.AddIndex(
            model_name="providerservicearea",
            index=models.Index(
                fields=["provider", "city"],
                name="idx_psa_prov_city",
            ),
        ),
        migrations.AddIndex(
            model_name="providerservicearea",
            index=models.Index(
                fields=["provider", "province"],
                name="idx_psa_prov_prov",
            ),
        ),
        migrations.AddIndex(
            model_name="providerservicearea",
            index=models.Index(
                fields=["provider", "is_active", "city"],
                name="idx_psa_act_city",
            ),
        ),
    ]
