# Generated by Django 5.2.11 on 2026-03-10 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_provider_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=10)),
                ('country', models.CharField(default='Canada', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='providers.provider')),
            ],
        ),
    ]
