# Generated by Django 5.2.11 on 2026-03-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_providerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='last_job_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
