# Generated by Django 5.2.11 on 2026-02-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_matching_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='providerservicearea',
            name='idx_psa_prov_city',
        ),
        migrations.RemoveIndex(
            model_name='providerservicearea',
            name='idx_psa_prov_prov',
        ),
        migrations.RemoveIndex(
            model_name='providerservicearea',
            name='idx_psa_act_city',
        ),
        migrations.RemoveIndex(
            model_name='providerservicetype',
            name='idx_pst_prov_st',
        ),
        migrations.RemoveIndex(
            model_name='providerservicetype',
            name='idx_pst_st_prov',
        ),
        migrations.RemoveIndex(
            model_name='providerservicetype',
            name='idx_pst_st_act_prov',
        ),
    ]
