# Generated by Django 5.2.11 on 2026-02-23 12:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0012_remove_providerservicearea_idx_psa_prov_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderBillingProfile',
            fields=[
                ('provider_billing_profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('self_employed', 'Self-employed'), ('company', 'Company')], max_length=20)),
                ('legal_name', models.CharField(blank=True, default='', max_length=200)),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('gst_hst_number', models.CharField(blank=True, default='', max_length=40)),
                ('qst_tvq_number', models.CharField(blank=True, default='', max_length=40)),
                ('neq_number', models.CharField(blank=True, default='', max_length=40)),
                ('bn_number', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.OneToOneField(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_billing_profile',
            },
        ),
        migrations.CreateModel(
            name='ProviderInvoiceSequence',
            fields=[
                ('provider_invoice_sequence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(blank=True, default='', max_length=30)),
                ('next_number', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.OneToOneField(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_seq', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_invoice_sequence',
            },
        ),
        migrations.CreateModel(
            name='ProviderCertificate',
            fields=[
                ('provider_certificate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cert_type', models.CharField(max_length=80)),
                ('cert_name', models.CharField(blank=True, default='', max_length=150)),
                ('taken_at', models.CharField(blank=True, default='', max_length=150)),
                ('issued_by', models.CharField(blank=True, default='', max_length=150)),
                ('issued_country', models.CharField(blank=True, default='', max_length=80)),
                ('issued_city', models.CharField(blank=True, default='', max_length=80)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expires_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('declared', 'Declared'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='declared', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_certificate',
                'indexes': [models.Index(fields=['provider', 'status'], name='ix_prov_cert_status'), models.Index(fields=['cert_type'], name='ix_prov_cert_type')],
            },
        ),
    ]
