# Generated by Django 5.2.11 on 2026-02-23 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_providerbillingprofile_providerinvoicesequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderTicket',
            fields=[
                ('provider_ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ref_type', models.CharField(max_length=30)),
                ('ref_id', models.BigIntegerField(db_index=True)),
                ('ticket_no', models.CharField(max_length=60)),
                ('amount_cents', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_ticket',
                'indexes': [models.Index(fields=['provider', 'created_at'], name='ix_provider_ticket_created')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'ticket_no'), name='uq_provider_ticket_no'), models.UniqueConstraint(fields=('provider', 'ref_type', 'ref_id'), name='uq_provider_ticket_ref')],
            },
        ),
    ]
