# Generated by Django 5.2.11 on 2026-03-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_providerlocation_grid_lat_providerlocation_grid_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermetrics',
            name='offers_accepted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providermetrics',
            name='offers_received_count',
            field=models.IntegerField(default=0),
        ),
    ]
