# Generated by Django 5.2.11 on 2026-03-10 02:48

from django.db import migrations, models


def backfill_provider_base_dispatch_score(apps, schema_editor):
    Provider = apps.get_model("providers", "Provider")
    ProviderMetrics = apps.get_model("providers", "ProviderMetrics")

    metrics_by_provider_id = {
        metrics.provider_id: metrics
        for metrics in ProviderMetrics.objects.all().only(
            "provider_id",
            "avg_response_time",
            "acceptance_rate",
            "completion_rate",
        )
    }

    for provider in Provider.objects.all().only("provider_id", "avg_rating"):
        metrics = metrics_by_provider_id.get(provider.provider_id)
        rating_score = (float(provider.avg_rating or 0.0) / 5.0) * 0.2

        if metrics is None:
            response_score = 0.5 * 0.15
            acceptance_score = 0.0
            completion_score = 0.0
        else:
            avg_response_time = float(metrics.avg_response_time or 0.0)
            response_value = 0.5 if avg_response_time <= 0 else max(0.0, 1.0 - (avg_response_time / 60.0))
            response_score = response_value * 0.15
            acceptance_score = max(0.0, min(float(metrics.acceptance_rate or 0.0), 1.0)) * 0.1
            completion_score = max(0.0, min(float(metrics.completion_rate or 0.0), 1.0)) * 0.1

        Provider.objects.filter(provider_id=provider.provider_id).update(
            base_dispatch_score=round(
                min(1.0, max(0.0, rating_score + response_score + acceptance_score + completion_score)),
                4,
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_providermetrics_offers_accepted_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='base_dispatch_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.RunPython(backfill_provider_base_dispatch_score, migrations.RunPython.noop),
    ]
