# Generated by Django 5.2.11 on 2026-02-23 13:09

from django.db import migrations, models
from django.db.models import F


def backfill_total_from_subtotal(apps, schema_editor):
    ProviderTicket = apps.get_model("providers", "ProviderTicket")
    ProviderTicket.objects.filter(total_cents=0).update(total_cents=F("subtotal_cents"))


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_providerticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name="providerticket",
            old_name="amount_cents",
            new_name="subtotal_cents",
        ),
        migrations.AddField(
            model_name='providerticket',
            name='stage',
            field=models.CharField(choices=[('estimate', 'Estimate'), ('final', 'Final')], default='estimate', max_length=20),
        ),
        migrations.AddField(
            model_name='providerticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('finalized', 'Finalized'), ('void', 'Void')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='providerticket',
            name='tax_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerticket',
            name='tax_region_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='providerticket',
            name='total_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.RunPython(backfill_total_from_subtotal, migrations.RunPython.noop),
    ]
