# Generated by Django 5.2.11 on 2026-03-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0016_provider_temporary_unavailable_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='accepts_scheduled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='accepts_urgent',
            field=models.BooleanField(default=True),
        ),
    ]
