# Generated by Django 5.2.11 on 2026-02-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0016_providerticketline'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerticketline',
            name='tax_rate_bps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='providerticketline',
            name='tax_region_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
