# Generated by Django 5.2.11 on 2026-02-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0018_provideruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='stripe_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='stripe_account_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='stripe_details_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
