# Generated by Django 5.2.11 on 2026-02-27 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0019_provider_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('billing_unit', models.CharField(choices=[('hour', 'Per Hour'), ('fixed', 'Fixed Price'), ('sqm', 'Per Square Meter'), ('km', 'Per Kilometer'), ('day', 'Per Day')], max_length=20)),
                ('price_cents', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.provider')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='providers.servicecategory')),
            ],
        ),
    ]
