# Generated by Django 5.2.11 on 2026-02-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0020_servicecategory_providerservice'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['province', 'city', 'is_active'], name='ix_provider_geo_active'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['category', 'is_active'], name='ix_psvc_cat_active'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['price_cents'], name='ix_psvc_price'),
        ),
    ]
