# Generated by Django 5.2.11 on 2026-02-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0021_provider_ix_provider_geo_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='acceptance_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='provider',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='provider',
            name='cancelled_jobs_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='completed_jobs_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
