# Generated by Django 5.2.11 on 2026-02-27 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientticket_snapshot_hash'),
        ('jobs', '0035_job_cancelled_by'),
        ('providers', '0022_provider_acceptance_rate_provider_avg_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderReview',
            fields=[
                ('provider_review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_review', to='jobs.job')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='providers.provider')),
            ],
        ),
    ]
