# Generated by Django 5.2.11 on 2026-02-28 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0023_providerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['province', 'city', 'name'],
                'indexes': [models.Index(fields=['province', 'city'], name='ix_servicezone_prov_city')],
                'constraints': [models.UniqueConstraint(fields=('province', 'city', 'name'), name='uq_servicezone_province_city_name')],
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='providers.servicezone'),
        ),
    ]
