# Generated by Django 5.2.11 on 2026-02-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0024_servicezone_provider_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceAnalyticsSnapshot',
            fields=[
                ('marketplace_analytics_snapshot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('snapshot', models.TextField()),
            ],
            options={
                'db_table': 'marketplace_analytics_snapshot',
                'ordering': ['-captured_at'],
            },
        ),
    ]
