# Generated by Django 5.2.11 on 2026-02-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0025_marketplaceanalyticssnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceanalyticssnapshot',
            name='snapshot_version',
            field=models.CharField(default='ANALYTICS_V1', max_length=50),
        ),
    ]
