# Generated by Django 5.2.11 on 2026-03-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0026_marketplaceanalyticssnapshot_snapshot_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='disputes_lost_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
