# Generated by Django 5.2.11 on 2026-03-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0027_provider_disputes_lost_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='quality_warning_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='restricted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
