# Generated by Django 5.2.11 on 2026-03-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0028_provider_quality_warning_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone_verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
