# Generated by Django 5.2.11 on 2026-03-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0029_provider_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='accepts_terms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='billing_profile_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='business_registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='provider',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='provider',
            name='profile_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='service_area',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
