# Generated by Django 5.2.11 on 2026-02-10 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('service_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSkill',
            fields=[
                ('service_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='service_type.servicetype')),
            ],
            options={
                'db_table': 'service_skill',
                'unique_together': {('service_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProviderServiceType',
            fields=[
                ('provider_service_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_type', models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed')], default='hourly', max_length=10)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='providers.provider')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='service_type.servicetype')),
            ],
            options={
                'db_table': 'provider_service_type',
                'unique_together': {('provider', 'service_type')},
            },
        ),
    ]
