# Generated by Django 5.2.11 on 2026-02-10 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerservicetype',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_services', to='service_type.servicetype'),
        ),
    ]
