# Generated by Django 5.2.11 on 2026-03-04 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('cert_type', models.CharField(max_length=100)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_certifications', to='service_type.servicetype')),
            ],
            options={
                'unique_together': {('service_type', 'province', 'cert_type')},
            },
        ),
    ]
