# Generated by Django 5.2.11 on 2026-03-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_type', '0002_requiredcertification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requiredcertification',
            unique_together={('service_type', 'province')},
        ),
        migrations.AddField(
            model_name='requiredcertification',
            name='certificate_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='requiredcertification',
            name='requires_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requiredcertification',
            name='requires_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requiredcertification',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_requirements', to='service_type.servicetype'),
        ),
        migrations.RemoveField(
            model_name='requiredcertification',
            name='cert_type',
        ),
        migrations.RemoveField(
            model_name='requiredcertification',
            name='is_mandatory',
        ),
    ]
