# Generated by Django 5.2.11 on 2026-02-12 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_type', '0002_alter_providerservicetype_service_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderServiceType',
        ),
    ]
