# Generated by Django 5.2.11 on 2026-03-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_type', '0003_alter_requiredcertification_unique_together_and_more'),
    ]



def _copy_servicetype_name_to_translations(apps, schema_editor):
    ServiceType = apps.get_model('service_type', 'ServiceType')
    for obj in ServiceType.objects.all():
        obj.name_en = obj.name
        if not obj.name_fr:
            obj.name_fr = obj.name
        if not obj.name_es:
            obj.name_es = obj.name
        obj.save(update_fields=['name_en', 'name_fr', 'name_es'])


class Migration(migrations.Migration):

    dependencies = [
        ('service_type', '0003_alter_requiredcertification_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_es',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_fr',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.RunPython(_copy_servicetype_name_to_translations, reverse_code=migrations.RunPython.noop),
    ]
