# Generated by Django 5.2.11 on 2026-03-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_type', '0004_servicetype_name_en_servicetype_name_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
