# Generated by Django 5.2.11 on 2026-03-04 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verification_attempts', models.IntegerField(default=0)),
                ('accepts_terms', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='ClientInvoiceSequence',
            fields=[
                ('client_invoice_sequence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(blank=True, default='', max_length=30)),
                ('next_number', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_seq', to='clients.client')),
            ],
            options={
                'db_table': 'client_invoice_sequence',
            },
        ),
        migrations.CreateModel(
            name='ClientTicket',
            fields=[
                ('client_ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ref_type', models.CharField(max_length=30)),
                ('ref_id', models.BigIntegerField(db_index=True)),
                ('ticket_no', models.CharField(max_length=60)),
                ('stage', models.CharField(choices=[('estimate', 'Estimate'), ('final', 'Final')], default='estimate', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('finalized', 'Finalized'), ('void', 'Void')], default='open', max_length=20)),
                ('subtotal_cents', models.BigIntegerField(default=0)),
                ('tax_cents', models.BigIntegerField(default=0)),
                ('total_cents', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('tax_region_code', models.CharField(blank=True, default='', max_length=20)),
                ('snapshot_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='clients.client')),
            ],
            options={
                'db_table': 'client_ticket',
            },
        ),
        migrations.CreateModel(
            name='ClientTicketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('line_type', models.CharField(choices=[('base', 'Base service'), ('extra', 'Extra'), ('fee', 'Fee'), ('adjust', 'Adjustment')], max_length=16)),
                ('description', models.CharField(max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price_cents', models.IntegerField(default=0)),
                ('line_subtotal_cents', models.IntegerField(default=0)),
                ('tax_rate_bps', models.IntegerField(default=0)),
                ('tax_cents', models.IntegerField(default=0)),
                ('line_total_cents', models.IntegerField(default=0)),
                ('tax_region_code', models.CharField(blank=True, max_length=10, null=True)),
                ('tax_code', models.CharField(blank=True, default='', max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='clients.clientticket')),
            ],
        ),
        migrations.AddIndex(
            model_name='clientticket',
            index=models.Index(fields=['client', 'created_at'], name='ix_client_ticket_created'),
        ),
        migrations.AddConstraint(
            model_name='clientticket',
            constraint=models.UniqueConstraint(fields=('client', 'ticket_no'), name='uq_client_ticket_no'),
        ),
        migrations.AddConstraint(
            model_name='clientticket',
            constraint=models.UniqueConstraint(fields=('client', 'ref_type', 'ref_id'), name='uq_client_ticket_ref'),
        ),
        migrations.AddIndex(
            model_name='clientticketline',
            index=models.Index(fields=['ticket', 'line_type'], name='ix_client_line_ticket_type'),
        ),
        migrations.AddConstraint(
            model_name='clientticketline',
            constraint=models.UniqueConstraint(fields=('ticket', 'line_no'), name='uq_client_ticket_line_no_per_ticket'),
        ),
    ]
