# Generated by Django 5.2.11 on 2026-02-23 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoiceSequence',
            fields=[
                ('client_invoice_sequence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(blank=True, default='', max_length=30)),
                ('next_number', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_seq', to='clients.client')),
            ],
            options={
                'db_table': 'client_invoice_sequence',
            },
        ),
        migrations.CreateModel(
            name='ClientTicket',
            fields=[
                ('client_ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ref_type', models.CharField(max_length=30)),
                ('ref_id', models.BigIntegerField(db_index=True)),
                ('ticket_no', models.CharField(max_length=60)),
                ('stage', models.CharField(choices=[('estimate', 'Estimate'), ('final', 'Final')], default='estimate', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('finalized', 'Finalized'), ('void', 'Void')], default='open', max_length=20)),
                ('subtotal_cents', models.BigIntegerField(default=0)),
                ('tax_cents', models.BigIntegerField(default=0)),
                ('total_cents', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('tax_region_code', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='clients.client')),
            ],
            options={
                'db_table': 'client_ticket',
                'indexes': [models.Index(fields=['client', 'created_at'], name='ix_client_ticket_created')],
                'constraints': [models.UniqueConstraint(fields=('client', 'ticket_no'), name='uq_client_ticket_no'), models.UniqueConstraint(fields=('client', 'ref_type', 'ref_id'), name='uq_client_ticket_ref')],
            },
        ),
    ]
