# Generated by Django 5.2.11 on 2026-02-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientinvoicesequence_clientticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTicketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('line_type', models.CharField(choices=[('base', 'Base service'), ('extra', 'Extra'), ('fee', 'Fee'), ('adjust', 'Adjustment')], max_length=16)),
                ('description', models.CharField(max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price_cents', models.IntegerField(default=0)),
                ('line_subtotal_cents', models.IntegerField(default=0)),
                ('tax_cents', models.IntegerField(default=0)),
                ('line_total_cents', models.IntegerField(default=0)),
                ('tax_region_code', models.CharField(blank=True, default='', max_length=16)),
                ('tax_code', models.CharField(blank=True, default='', max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='clients.clientticket')),
            ],
            options={
                'indexes': [models.Index(fields=['ticket', 'line_type'], name='ix_client_line_ticket_type')],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'line_no'), name='uq_client_ticket_line_no_per_ticket')],
            },
        ),
    ]
