# Generated by Django 5.2.11 on 2026-03-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_languages_spoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientServiceAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=100)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("access_notes", models.TextField(blank=True, default="")),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_addresses",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "client_service_address",
                "ordering": ("-is_default", "label", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="clientserviceaddress",
            index=models.Index(fields=["client", "is_active"], name="ix_csrvaddr_client_active"),
        ),
    ]
