# Generated by Django 5.2.11 on 2026-02-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientticketline_tax_rate_bps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientticket',
            name='snapshot_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
