"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

STRIPE_MODE = os.getenv("STRIPE_MODE", "test")

def _first_env(*names):
    for name in names:
        value = os.getenv(name)
        if value:
            return value
    return None


if STRIPE_MODE == "live":
    STRIPE_SECRET_KEY = _first_env("STRIPE_SECRET_KEY_LIVE", "STRIPE_SECRET_KEY")
    STRIPE_WEBHOOK_SECRET = _first_env(
        "STRIPE_WEBHOOK_SECRET_LIVE",
        "STRIPE_WEBHOOK_SECRET",
    )
    STRIPE_PUBLISHABLE_KEY = _first_env(
        "STRIPE_PUBLISHABLE_KEY_LIVE",
        "STRIPE_PUBLISHABLE_KEY",
    )
else:
    STRIPE_SECRET_KEY = _first_env("STRIPE_SECRET_KEY_TEST", "STRIPE_SECRET_KEY")
    STRIPE_WEBHOOK_SECRET = _first_env(
        "STRIPE_WEBHOOK_SECRET_TEST",
        "STRIPE_WEBHOOK_SECRET",
    )
    STRIPE_PUBLISHABLE_KEY = _first_env(
        "STRIPE_PUBLISHABLE_KEY_TEST",
        "STRIPE_PUBLISHABLE_KEY",
    )

if STRIPE_SECRET_KEY:
    os.environ.setdefault("STRIPE_SECRET_KEY", STRIPE_SECRET_KEY)
if STRIPE_WEBHOOK_SECRET:
    os.environ.setdefault("STRIPE_WEBHOOK_SECRET", STRIPE_WEBHOOK_SECRET)
if STRIPE_PUBLISHABLE_KEY:
    os.environ.setdefault("STRIPE_PUBLISHABLE_KEY", STRIPE_PUBLISHABLE_KEY)

PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "http://localhost:8000").rstrip("/")

STRIPE_ONBOARDING_REFRESH_URL = os.getenv(
    "STRIPE_ONBOARDING_REFRESH_URL",
    f"{PUBLIC_BASE_URL}/stripe/onboarding/refresh/",
)
STRIPE_ONBOARDING_RETURN_URL = os.getenv(
    "STRIPE_ONBOARDING_RETURN_URL",
    f"{PUBLIC_BASE_URL}/stripe/onboarding/complete/",
)

if not STRIPE_SECRET_KEY:
    raise RuntimeError("Stripe secret key not configured")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d%3ebi)1nzk6*y3!mtijivxes#c7u)_%whx!05w^3g2gqhq!q)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOW_LEDGER_REBUILD = False

def _csv_env(name, default):
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


ALLOWED_HOSTS = _csv_env(
    "DJANGO_ALLOWED_HOSTS",
    "127.0.0.1,localhost,[::1],.ngrok-free.dev,.trycloudflare.com",
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "clients.apps.ClientsConfig",
    "payments.apps.PaymentsConfig",
    "providers.apps.ProvidersConfig",
    "settlements.apps.SettlementsConfig",
    'service_type',
    'workers',
    'assignments.apps.AssignmentsConfig',
    "jobs.apps.JobsConfig",
    "ui.apps.UiConfig",

]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": "Nodo",  # <-- cambia esto por el nombre real de tu BD
        "HOST": r".\SQLEXPRESS",
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
            "TrustServerCertificate": "yes",
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Optional override for auto evidence destination.
NODO_EVIDENCE_DIR = None
