# Generated by Django 5.2.11 on 2026-02-10 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_job_client_alter_job_selected_provider_and_more'),
        ('providers', '0001_initial'),
        ('workers', '0003_alter_worker_city_alter_worker_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assignment_status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='jobs.job')),
                ('provider', models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_assignments', to='providers.provider')),
                ('worker', models.ForeignKey(blank=True, db_column='worker_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_assignments', to='workers.worker')),
            ],
            options={
                'db_table': 'job_assignment',
            },
        ),
    ]
