# Generated by Django 5.2.11 on 2026-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(choices=[('none', 'None'), ('provider', 'Provider'), ('client', 'Client'), ('sponsor', 'Sponsor')], default='none', max_length=16)),
                ('model', models.CharField(choices=[('off', 'Off'), ('commission', 'Commission'), ('subscription', 'Subscription'), ('ads', 'Ads')], default='off', max_length=16)),
                ('status', models.CharField(choices=[('off', 'Off'), ('pending', 'Pending'), ('charged', 'Charged'), ('waived', 'Waived')], default='off', max_length=16)),
                ('amount_cents', models.IntegerField(default=0)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assignment_fee',
            },
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assignment_status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='assigned', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_assignment',
            },
        ),
    ]
