# Generated by Django 5.2.11 on 2026-03-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('jobs', '0001_initial'),
        ('providers', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignment',
            name='job',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='provider',
            field=models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_assignments', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='worker',
            field=models.ForeignKey(blank=True, db_column='worker_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_assignments', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='assignmentfee',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='assignments.jobassignment'),
        ),
        migrations.AddConstraint(
            model_name='jobassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('job',), name='uq_job_assignment_one_active_per_job'),
        ),
    ]
