# Generated by Django 5.2.11 on 2026-02-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_jobassignment_is_active_and_more'),
        ('jobs', '0002_job_client_alter_job_selected_provider_and_more'),
        ('providers', '0001_initial'),
        ('workers', '0003_alter_worker_city_alter_worker_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='jobassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('job',), name='uq_job_assignment_one_active_per_job'),
        ),
    ]
