# Generated by Django 5.2.11 on 2026-02-21 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_jobassignment_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(choices=[('none', 'None'), ('provider', 'Provider'), ('client', 'Client'), ('sponsor', 'Sponsor')], default='none', max_length=16)),
                ('model', models.CharField(choices=[('off', 'Off'), ('commission', 'Commission'), ('subscription', 'Subscription'), ('ads', 'Ads')], default='off', max_length=16)),
                ('status', models.CharField(choices=[('off', 'Off'), ('pending', 'Pending'), ('charged', 'Charged'), ('waived', 'Waived')], default='off', max_length=16)),
                ('amount_cents', models.IntegerField(default=0)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='assignments.jobassignment')),
            ],
            options={
                'db_table': 'assignment_fee',
            },
        ),
    ]
