# Generated by Django 5.2.11 on 2026-03-01 16:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('client', 'Client'), ('provider', 'Provider')], max_length=20)),
                ('actor_id', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phone_verification',
                'indexes': [models.Index(fields=['actor_type', 'actor_id'], name='phone_verif_actor_t_18f8a6_idx'), models.Index(fields=['phone_number'], name='phone_verif_phone_n_574ae0_idx')],
            },
        ),
    ]
