# Generated by Django 5.2.11 on 2026-03-04 17:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('client', 'Client'), ('provider', 'Provider')], max_length=20)),
                ('actor_id', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phone_verification',
                'indexes': [models.Index(fields=['actor_type', 'actor_id'], name='phone_verif_actor_t_18f8a6_idx'), models.Index(fields=['phone_number'], name='phone_verif_phone_n_574ae0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OTP_IP_RATE_LIMIT', 'OTP IP Rate Limit'), ('OTP_PHONE_RATE_LIMIT', 'OTP Phone Rate Limit'), ('OTP_DAILY_LIMIT', 'OTP Daily Limit'), ('OTP_REQUEST_COOLDOWN', 'OTP Request Cooldown'), ('OTP_ABUSE_BLOCK', 'OTP Abuse Block')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('actor_type', models.CharField(blank=True, max_length=20, null=True)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_event',
                'indexes': [models.Index(fields=['event_type'], name='security_ev_event_t_b3c533_idx'), models.Index(fields=['phone_number'], name='security_ev_phone_n_9366c0_idx'), models.Index(fields=['created_at'], name='security_ev_created_ca8d45_idx')],
            },
        ),
    ]
