# Generated by Django 5.2.11 on 2026-03-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OTP_IP_RATE_LIMIT', 'OTP IP Rate Limit'), ('OTP_PHONE_RATE_LIMIT', 'OTP Phone Rate Limit'), ('OTP_DAILY_LIMIT', 'OTP Daily Limit'), ('OTP_REQUEST_COOLDOWN', 'OTP Request Cooldown'), ('OTP_ABUSE_BLOCK', 'OTP Abuse Block')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('actor_type', models.CharField(blank=True, max_length=20, null=True)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_event',
                'indexes': [models.Index(fields=['event_type'], name='security_ev_event_t_b3c533_idx'), models.Index(fields=['phone_number'], name='security_ev_phone_n_9366c0_idx'), models.Index(fields=['created_at'], name='security_ev_created_ca8d45_idx')],
            },
        ),
    ]
