# Generated by Django 5.2.11 on 2026-03-04 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('jobs', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('provider_responded', 'Provider Responded'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=30)),
                ('resolution_type', models.CharField(blank=True, choices=[('refund_50', 'Refund 50%'), ('refund_100', 'Refund 100%'), ('no_refund', 'No Refund')], max_length=30, null=True)),
                ('client_reason', models.TextField()),
                ('provider_response', models.TextField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('provider_responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='jobs.job')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='providers.provider')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySettlementClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('is_global', models.BooleanField(default=False)),
                ('total_gross_cents', models.BigIntegerField(default=0)),
                ('total_provider_cents', models.BigIntegerField(default=0)),
                ('total_platform_revenue_cents', models.BigIntegerField(default=0)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('total_gross_cents', models.BigIntegerField(default=0)),
                ('total_tax_cents', models.BigIntegerField(default=0)),
                ('total_fee_cents', models.BigIntegerField(default=0)),
                ('total_net_provider_cents', models.BigIntegerField(default=0)),
                ('total_platform_revenue_cents', models.BigIntegerField(default=0)),
                ('total_jobs', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('closed', 'Closed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_payout_date', models.DateField(blank=True, help_text='Scheduled payout date (Wednesday following settlement period)', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_settlement',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('client_refund', 'Client refund'), ('provider_deduction', 'Provider deduction'), ('platform_fee_reversal', 'Platform fee reversal')], max_length=40)),
                ('amount_cents', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_adjustments', to='settlements.jobdispute')),
                ('ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='jobs.platformledgerentry')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_adjustments', to='settlements.providersettlement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementExportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SETTLEMENT_EXPORTED', 'SETTLEMENT_EXPORTED')], default='SETTLEMENT_EXPORTED', editable=False, max_length=50)),
                ('mode', models.CharField(choices=[('single', 'single'), ('range', 'range')], max_length=10)),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('settlements_count', models.PositiveIntegerField()),
                ('total_rows', models.PositiveIntegerField()),
                ('total_gross_cents', models.BigIntegerField()),
                ('total_tax_cents', models.BigIntegerField()),
                ('total_fee_cents', models.BigIntegerField()),
                ('total_net_provider_cents', models.BigIntegerField()),
                ('total_platform_revenue_cents', models.BigIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('file_path', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settlements.providersettlement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField()),
                ('reference', models.CharField(max_length=255)),
                ('amount_cents', models.BigIntegerField()),
                ('stripe_transfer_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('stripe_idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_status', models.CharField(db_index=True, default='initiated', max_length=50)),
                ('stripe_environment', models.CharField(db_index=True, default='test', max_length=10)),
                ('stripe_failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executed_settlement_payments', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_payment', to='settlements.providersettlement')),
            ],
            options={
                'db_table': 'settlement_payment',
                'ordering': ['-executed_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobdispute',
            constraint=models.UniqueConstraint(fields=('job',), name='uq_job_single_dispute'),
        ),
        migrations.AddIndex(
            model_name='monthlysettlementclose',
            index=models.Index(fields=['period_start', 'period_end'], name='settlements_period__3da834_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlysettlementclose',
            index=models.Index(fields=['provider'], name='settlements_provide_3fa42b_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlysettlementclose',
            constraint=models.UniqueConstraint(fields=('provider', 'period_start', 'period_end', 'is_global'), name='uq_monthly_close_unique_scope'),
        ),
        migrations.AddConstraint(
            model_name='providersettlement',
            constraint=models.UniqueConstraint(fields=('provider', 'period_start', 'period_end'), name='uq_provider_settlement_period'),
        ),
        migrations.AddConstraint(
            model_name='providersettlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), ('paid_at__isnull', False)), models.Q(models.Q(('status', 'paid'), _negated=True), ('paid_at__isnull', True)), _connector='OR'), name='ck_provider_settlement_paid_at_consistency'),
        ),
        migrations.AddIndex(
            model_name='ledgeradjustment',
            index=models.Index(fields=['ledger_entry', 'created_at'], name='settlements_ledger__1f438e_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeradjustment',
            index=models.Index(fields=['adjustment_type'], name='settlements_adjustm_efd14a_idx'),
        ),
    ]
