# Generated by Django 5.2.11 on 2026-02-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0017_providerticketline_tax_rate_bps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('total_gross_cents', models.BigIntegerField(default=0)),
                ('total_tax_cents', models.BigIntegerField(default=0)),
                ('total_fee_cents', models.BigIntegerField(default=0)),
                ('total_net_provider_cents', models.BigIntegerField(default=0)),
                ('total_platform_revenue_cents', models.BigIntegerField(default=0)),
                ('total_jobs', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_settlement',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'period_start', 'period_end'), name='uq_provider_settlement_period')],
            },
        ),
    ]
