# Generated by Django 5.2.11 on 2026-02-24 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementExportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SETTLEMENT_EXPORTED', 'SETTLEMENT_EXPORTED')], default='SETTLEMENT_EXPORTED', editable=False, max_length=50)),
                ('mode', models.CharField(choices=[('single', 'single'), ('range', 'range')], max_length=10)),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('settlements_count', models.PositiveIntegerField()),
                ('total_rows', models.PositiveIntegerField()),
                ('total_gross_cents', models.BigIntegerField()),
                ('total_tax_cents', models.BigIntegerField()),
                ('total_fee_cents', models.BigIntegerField()),
                ('total_net_provider_cents', models.BigIntegerField()),
                ('total_platform_revenue_cents', models.BigIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('file_path', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settlements.providersettlement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
