# Generated by Django 5.2.11 on 2026-02-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0017_providerticketline_tax_rate_bps_and_more'),
        ('settlements', '0002_settlementexportevidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySettlementClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('is_global', models.BooleanField(default=False)),
                ('total_gross_cents', models.BigIntegerField(default=0)),
                ('total_provider_cents', models.BigIntegerField(default=0)),
                ('total_platform_revenue_cents', models.BigIntegerField(default=0)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes', to='providers.provider')),
            ],
            options={
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='settlements_period__3da834_idx'), models.Index(fields=['provider'], name='settlements_provide_3fa42b_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'period_start', 'period_end', 'is_global'), name='uq_monthly_close_unique_scope')],
            },
        ),
    ]
