# Generated by Django 5.2.11 on 2026-02-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0003_monthlysettlementclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersettlement',
            name='scheduled_payout_date',
            field=models.DateField(blank=True, help_text='Scheduled payout date (Wednesday following settlement period)', null=True),
        ),
        migrations.AlterField(
            model_name='providersettlement',
            name='status',
            field=models.CharField(choices=[('calculated', 'Calculated'), ('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
