# Generated by Django 5.2.11 on 2026-02-25 12:37

from django.db import migrations, models
from django.utils import timezone


def normalize_settlement_status_and_paid_at(apps, schema_editor):
    ProviderSettlement = apps.get_model("settlements", "ProviderSettlement")

    # If paid_at is set, status must be paid.
    ProviderSettlement.objects.exclude(paid_at__isnull=True).exclude(
        status="paid"
    ).update(status="paid")

    # If status is paid, paid_at must exist.
    ProviderSettlement.objects.filter(status="paid", paid_at__isnull=True).update(
        paid_at=timezone.now()
    )

    # Normalize legacy status values to the new lifecycle.
    ProviderSettlement.objects.filter(status="calculated").update(status="draft")
    ProviderSettlement.objects.filter(status="pending").update(status="draft")
    ProviderSettlement.objects.filter(status="approved").update(status="closed")


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0018_provideruser'),
        ('settlements', '0004_providersettlement_scheduled_payout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersettlement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('closed', 'Closed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.RunPython(
            normalize_settlement_status_and_paid_at,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='providersettlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), ('paid_at__isnull', False)), models.Q(models.Q(('status', 'paid'), _negated=True), ('paid_at__isnull', True)), _connector='OR'), name='ck_provider_settlement_paid_at_consistency'),
        ),
    ]
