# Generated by Django 5.2.11 on 2026-02-25 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientticketline_tax_rate_bps_and_more'),
        ('jobs', '0032_platformledgerentry_uniq_final_ledger_per_job'),
        ('providers', '0018_provideruser'),
        ('settlements', '0005_alter_providersettlement_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('provider_responded', 'Provider Responded'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=30)),
                ('resolution_type', models.CharField(blank=True, choices=[('refund_50', 'Refund 50%'), ('refund_100', 'Refund 100%'), ('no_refund', 'No Refund')], max_length=30, null=True)),
                ('client_reason', models.TextField()),
                ('provider_response', models.TextField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('provider_responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='jobs.job')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='providers.provider')),
            ],
            options={
                'ordering': ['-opened_at'],
                'constraints': [models.UniqueConstraint(fields=('job',), name='uq_job_single_dispute')],
            },
        ),
    ]
