# Generated by Django 5.2.11 on 2026-02-25 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_platformledgerentry_uniq_final_ledger_per_job'),
        ('settlements', '0006_jobdispute'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('client_refund', 'Client refund'), ('provider_deduction', 'Provider deduction'), ('platform_fee_reversal', 'Platform fee reversal')], max_length=40)),
                ('amount_cents', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_adjustments', to='settlements.jobdispute')),
                ('ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='jobs.platformledgerentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ledger_entry', 'created_at'], name='settlements_ledger__1f438e_idx'), models.Index(fields=['adjustment_type'], name='settlements_adjustm_efd14a_idx')],
            },
        ),
    ]
