# Generated by Django 5.2.11 on 2026-02-25 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0007_ledgeradjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeradjustment',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_adjustments', to='settlements.providersettlement'),
        ),
    ]
