# Generated by Django 5.2.11 on 2026-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0009_settlementpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementpayment',
            name='stripe_failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementpayment',
            name='stripe_idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settlementpayment',
            name='stripe_status',
            field=models.CharField(db_index=True, default='initiated', max_length=50),
        ),
        migrations.AddField(
            model_name='settlementpayment',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
