# Generated by Django 5.2.11 on 2026-02-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0010_settlementpayment_stripe_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementpayment',
            name='stripe_environment',
            field=models.CharField(db_index=True, default='test', max_length=10),
        ),
    ]
