# Generated by Django 5.2.11 on 2026-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('accepts_terms', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(default='Canada', max_length=100)),
                ('province', models.CharField(blank=True, choices=[('QC', 'Québec')], max_length=100, null=True)),
                ('city', models.CharField(blank=True, choices=[('Montreal', 'Montréal'), ('Laval', 'Laval'), ('Longueuil', 'Longueuil'), ('Brossard', 'Brossard'), ('Saint-Lambert', 'Saint-Lambert'), ('Terrebonne', 'Terrebonne'), ('Mascouche', 'Mascouche'), ('Repentigny', 'Repentigny'), ('Blainville', 'Blainville'), ('Boisbriand', 'Boisbriand'), ('Rosemere', 'Rosemère'), ('Lorraine', 'Lorraine'), ('Sainte-Therese', 'Sainte-Thérèse'), ('Mirabel', 'Mirabel'), ('Saint-Eustache', 'Saint-Eustache'), ('Deux-Montagnes', 'Deux-Montagnes'), ('Sainte-Marthe-sur-le-Lac', 'Sainte-Marthe-sur-le-Lac'), ('Pointe-Calumet', 'Pointe-Calumet'), ('Oka', 'Oka'), ('Saint-Jerome', 'Saint-Jérôme')], max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('availability_mode', models.CharField(default='manual', max_length=20)),
                ('is_available_now', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('disputes_lost_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'worker',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
