# Generated by Django 5.2.11 on 2026-02-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_remove_worker_provider_remove_worker_worker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.CharField(blank=True, choices=[('Montreal', 'Montréal'), ('Laval', 'Laval'), ('Longueuil', 'Longueuil'), ('Brossard', 'Brossard'), ('Saint-Lambert', 'Saint-Lambert'), ('Terrebonne', 'Terrebonne'), ('Mascouche', 'Mascouche'), ('Repentigny', 'Repentigny'), ('Blainville', 'Blainville'), ('Boisbriand', 'Boisbriand'), ('Rosemere', 'Rosemère'), ('Lorraine', 'Lorraine'), ('Sainte-Therese', 'Sainte-Thérèse'), ('Mirabel', 'Mirabel'), ('Saint-Eustache', 'Saint-Eustache'), ('Deux-Montagnes', 'Deux-Montagnes'), ('Sainte-Marthe-sur-le-Lac', 'Sainte-Marthe-sur-le-Lac'), ('Pointe-Calumet', 'Pointe-Calumet'), ('Oka', 'Oka'), ('Saint-Jerome', 'Saint-Jérôme')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='province',
            field=models.CharField(blank=True, choices=[('QC', 'Québec')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
