# Generated by Django 5.2.11 on 2026-03-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_worker_city_alter_worker_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='disputes_lost_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
