# Generated by Django 5.2.11 on 2026-03-13 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("client", "Client"), ("provider", "Provider"), ("worker", "Worker")], max_length=20)),
                ("platform", models.CharField(choices=[("ios", "iOS"), ("android", "Android")], max_length=20)),
                ("token", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_push_device",
                "indexes": [
                    models.Index(fields=["user", "role", "is_active"], name="notificatio_user_id_f914d7_idx"),
                    models.Index(fields=["platform", "is_active"], name="notificatio_platfor_31460d_idx"),
                ],
            },
        ),
    ]
