# Generated by Django 5.2.11 on 2026-03-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_jobevent_live_metadata_and_event_types"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushDispatchAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("stub_sent", "Stub sent"), ("failed", "Failed")], default="stub_sent", max_length=20)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("response_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_attempts",
                        to="notifications.pushdevice",
                    ),
                ),
                (
                    "job_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_dispatch_attempts",
                        to="jobs.jobevent",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_push_dispatch_attempt",
                "indexes": [
                    models.Index(fields=["job_event", "created_at"], name="notificatio_job_eve_40e6df_idx"),
                    models.Index(fields=["device", "created_at"], name="notificatio_device__d86a52_idx"),
                ],
            },
        ),
    ]
