# Generated by Django 5.2.11 on 2026-03-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_pushdispatchattempt_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='notificatio_user_id_4326f1_idx',
            old_name='notificatio_user_id_f914d7_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='notificatio_platfor_dba628_idx',
            old_name='notificatio_platfor_31460d_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdispatchattempt',
            new_name='notificatio_job_eve_8635d2_idx',
            old_name='notificatio_job_eve_40e6df_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdispatchattempt',
            new_name='notificatio_device__000491_idx',
            old_name='notificatio_device__d86a52_idx',
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20),
        ),
    ]
